module BANK_TYPE
  VISA = "VISA"
  MASTERCARD = "MASTERCARD"
  AMEX = "AMERICAN EXPRESS"
end

module BANK_NUMBER
  VISA_NUMBER = "4";
  AMEX_NUMBER = %w[34 37];
  MASTERCARD_NUMBER = [51, 52, 53, 54, 55];
end